### ISSUE TITLE
jq 1.5 Fails to Build on Solaris/SmartOS

### ISSUE THREAD

**Issue by colstrom** [stedolan/jq#1196]
```
$ make
make  all-am
make[1]: Entering directory '/build/jq'
  CC       locfile.lo
  CC       bytecode.lo
  CC       compile.lo
  CC       execute.lo
  CC       builtin.lo
In file included from /usr/include/sys/time.h:27:0,
                 from builtin.c:4:
/usr/include/sys/feature_tests.h:396:2: error: #error "Compiler or options invalid for pre-UNIX 03 X/Open applications 	and pre-2001 POSIX applications"
 #error "Compiler or options invalid for pre-UNIX 03 X/Open applications \
  ^
builtin.c: In function 'my_mktime':
builtin.c:1041:3: warning: implicit declaration of function 'timegm' [-Wimplicit-function-declaration]
   return timegm(tm);
   ^
builtin.c: In function 'f_strptime':
builtin.c:1065:3: warning: implicit declaration of function 'strptime' [-Wimplicit-function-declaration]
   const char *end = strptime(input, fmt, &tm);
   ^
builtin.c:1065:21: warning: initialization makes pointer from integer without a cast
   const char *end = strptime(input, fmt, &tm);
                     ^
builtin.c: In function 'f_gmtime':
builtin.c:1152:3: warning: implicit declaration of function 'gmtime_r' [-Wimplicit-function-declaration]
   tmp = gmtime_r(&secs, &tm);
   ^
builtin.c:1152:7: warning: assignment makes pointer from integer without a cast
   tmp = gmtime_r(&secs, &tm);
       ^
builtin.c: In function 'f_now':
builtin.c:1211:18: error: storage size of 'tv' isn't known
   struct timeval tv;
                  ^
builtin.c:1212:3: warning: implicit declaration of function 'gettimeofday' [-Wimplicit-function-declaration]
   if (gettimeofday(&tv, NULL) == -1)
   ^
builtin.c:1211:18: warning: unused variable 'tv' [-Wunused-variable]
   struct timeval tv;
                  ^
builtin.c:1215:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[1]: *** [Makefile:910: builtin.lo] Error 1
make[1]: Leaving directory '/build/jq'
make: *** [Makefile:733: all] Error 2
```

**Comment by colstrom** [comment]
Checked out from the `jq-1.5` tag in git. All noted dependencies met (autoconf, bison, automake, make, flex, libtool). If there's any other details I can provide to clarify, just let me know.

**Comment by AttilaFueloep** [comment]
I've just committed PR #1202 which should fix your problem. Could you please try out master 
from [https://github.com/AttilaFueloep/jq](url).

**Comment by colstrom** [comment]
@AttilaFueloep Thanks!

It still fails to build, but with a different error this time...

Steps taken for context:

```
cd /build/jq
git fetch origin pull/1202/head:PR1202
git checkout PR1202
(autoreconf -i && ./configure && make clean && make) 2>&1 | tee build.log
```

Log attached:
- [build.log.txt](https://github.com/stedolan/jq/files/411642/build.log.txt)

(using `gcc 4.9.3` if that helps)

**Comment by AttilaFueloep** [comment]
Could you please try if replacing 
`#define _XOPEN_SOURCE` with `#define _XOPEN_SOURCE 500` in `src/builtin.c` works? 

Sorry, I've no Solaris box and SmartOS and Solaris seems to differ more than I thought.

**Comment by colstrom** [comment]
Same error.

I'm actually running this on SmartOS, if that helps.

**Comment by AttilaFueloep** [comment]
This standards stuff is a can of worms. Can you pull again?  
I just pushed a version which compiles on my SmartOS box.
Sorry for the inconvenience.

**Comment by colstrom** [comment]
Huzzah, successful build!

**Comment by AttilaFueloep** [comment]
Nice!

BTW the next pkgrsc version 2016Q3 should include a binary package for devel/jq.
Jonathan just committed my PR.

**Comment by colstrom** [comment]
Fantastic. Thanks for the assistance!

**Comment by AttilaFueloep** [comment]
You're welcome.

PR #1204 fixes the issue. I closed PR #1202 since it's incomplete.
