### ISSUE TITLE
Assigning to nan fails

### ISSUE THREAD

**Issue by erikbrinkman** [stedolan/jq#1316]
For some reason, assigning to a field that contains a nan value failes. MWE:

```
jq -n '[nan] | .[0] = null'
```

fails with "jq: error (at <unknown>): Invalid path expression with result null". This seems to happen when trying to assign any value that currently contains a nan, and applies to objects as well:

```
jq -n '{a:nan} | .a = null'
```

The error is being thrown in execute.c, but otherwise I see no obvious reasons why this is happening. Here's the debug trace and disasembly for the first example:

```
0000 TOP
0001 DUP
0002 LOADK []
0004 STOREV $collect:0
0007 FORK 0016
0009 CALL_BUILTIN nan
0012 APPEND $collect:0
0015 BACKTRACK
0016 LOADVN $collect:0
0019 CALL_JQ _assign:1 @lambda:2 @lambda:3
0027 RET
path:0:
  [params: arg]
  0000 PATH_BEGIN
  0001 CALL_JQ arg:0
  0005 PATH_END
  0006 RET
_assign:1:
  [params: paths, value]
  0000 DUP
  0001 CALL_JQ value:1
  0005 STOREV $v:0
  0008 DUP
  0009 STOREV $reduce:1
  0012 FORK 0044
  0014 DUPN
  0015 CALL_JQ path:0^1 @lambda:0
  0021 STOREV $p:2
  0024 LOADVN $reduce:1
  0027 SUBEXP_BEGIN
  0028 LOADV $v:0
  0031 SUBEXP_END
  0032 SUBEXP_BEGIN
  0033 LOADV $p:2
  0036 SUBEXP_END
  0037 CALL_BUILTIN setpath
  0040 STOREV $reduce:1
  0043 BACKTRACK
  0044 LOADVN $reduce:1
  0047 RET
  @lambda:0:
    0000 TAIL_CALL_JQ paths:0^1
    0004 RET
@lambda:2:
  0000 SUBEXP_BEGIN
  0001 LOADK 0
  0003 SUBEXP_END
  0004 INDEX
  0005 RET
@lambda:3:
  0000 LOADK null
  0002 RET

0000 TOP	
0001 DUP	null
0002 LOADK []	null
0004 STOREV $collect:0	[]
V0 = [] (2)
0007 FORK 0016	
0009 CALL_BUILTIN nan	null
0012 APPEND $collect:0	null
0015 BACKTRACK	
0007 FORK 0016		<backtracking>
0016 LOADVN $collect:0	null
V0 = [null] (1)
0019 CALL_JQ _assign:1 @lambda:2 @lambda:3	[null] (1)
0000 DUP	[null] (1)
0001 CALL_JQ value:1	[null] (2)
0000 LOADK null	[null] (2)
0002 RET	null
0005 STOREV $v:0	null
V0 = null (1)
0008 DUP	[null] (1)
0009 STOREV $reduce:1	[null] (2)
V1 = [null] (2)
0012 FORK 0044	
0014 DUPN	[null] (2)
0015 CALL_JQ path:0^1 @lambda:0	[null] (3)
0000 PATH_BEGIN	[null] (3)
0001 CALL_JQ arg:0	[null] (4)
0000 TAIL_CALL_JQ paths:0^1	[null] (4)
0000 SUBEXP_BEGIN	[null] (4)
0001 LOADK 0	[null] (5)
0003 SUBEXP_END	0 | [null] (4)
0004 INDEX	[null] (4) | 0
0005 RET	null
0005 PATH_END	null | null
0000 PATH_BEGIN		<backtracking>
0012 FORK 0044		<backtracking>
jq: error (at <unknown>): Invalid path expression with result null
```

**Comment by pkoppstein** [comment]
This problem has been fixed since the release of 1.5:

    $ jq1.5 -n '{a:nan} | .a = null'
    jq: error (at <unknown>): Invalid path expression with result null

    $ jq -V
    jq-1.5rc2-150-g1740fd0
    $ jq -nc '{a:nan} | .a = null'
    {"a":null}

**Comment by erikbrinkman** [comment]
I forgot to check closed issues. This is not fixed on the tag "jq-1.5", but it is fixed on master.
