### ISSUE TITLE
test failures on macOS 10.12

### ISSUE THREAD

**Issue by chdiza** [stedolan/jq#1415]
When trying to build from master on 10.12.4, I get the following test failure: https://gist.github.com/chdiza/762c86adaf40bfef2bdd889485eaa547

The test-suite.log is here:  https://gist.github.com/chdiza/a28e34301fe058b8759ce092a525a704

This happens whether or not I build against the enclosed oniguruma.

**Comment by nicowilliams** [comment]
That's... `strptime()` being broken on OS X.  Fantastic.  I guess I get to write code to deal with that.  Or not.

**Comment by nicowilliams** [comment]
We already have an issue open for OS X `strptime()` issues, #929.

See also http://stackoverflow.com/questions/31984002/why-does-strptime-behave-differently-on-osx-and-on-linux.  The OS X man page for [`strptime`](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/strptime.3.html) is woefully brief.  It seems that we need to compute `tm_wday` and `tm_yday` ourselves.

I don't think I'll be fixing this anytime soon, though I'll probably paper this over in the test.

**Comment by nicowilliams** [comment]
Ahhh, right, `timegm()` will set `tm_wday` and `tm_yday`.

**Comment by nicowilliams** [comment]
@chdiza I've pushed an attempt to fix this.  Can you please test.

**Comment by chdiza** [comment]
@nicowilliams Thanks.  I tested it and I still get the same test failure, with the same `test-suite.log`.

**Comment by nicowilliams** [comment]
@chdiza I've pushed c538237 to try once more to fix this.  Can you check it?

**Comment by chdiza** [comment]
@nicowilliams Getting closer, at least!  The same test fails, but this time the `testsuite.log` says something different:
```
====================================================
   jq 1.5rc2-243-gc538237-dirty: ./test-suite.log
====================================================

# TOTAL: 7
# PASS:  6
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/optionaltest
========================

Testing '[strptime("%Y-%m-%dT%H:%M:%SZ")|(.,mktime)]' at line number 4
Testing 'last(range(365 * 199)|("1900-03-01T01:02:03Z"|strptime("%Y-%m-%dT%H:%M:%SZ")|mktime) + (86400 * .)|strftime("%Y-%m-%dT%H:%M:%SZ")|strptime("%Y-%m-%dT%H:%M:%SZ"))' at line number 9
*** Insufficient results for test at line number 11: last(range(365 * 199)|("1900-03-01T01:02:03Z"|strptime("%Y-%m-%dT%H:%M:%SZ")|mktime) + (86400 * .)|strftime("%Y-%m-%dT%H:%M:%SZ")|strptime("%Y-%m-%dT%H:%M:%SZ"))
Testing 'strftime("%A, %B %e, %Y")' at line number 14
2 of 3 tests passed (0 malformed)
FAIL tests/optionaltest (exit status: 1)
```

**Comment by chdiza** [comment]
Hopefully that's an easy fix.  If not, instead of spending even more time on this it'd be just fine with me if this particular test is simply skipped on macOS.

**Comment by nicowilliams** [comment]
@chdiza Yeah, maybe.

Can you show us the output of this:

```
$ jq -n 'last(range(365 * 199)|("1900-03-01T01:02:03Z"|strptime("%Y-%m-%dT%H:%M:%SZ")|mktime) + (86400 * .)|strftime("%Y-%m-%dT%H:%M:%SZ")|strptime("%Y-%m-%dT%H:%M:%SZ"))' 
```

I mean, the test log implies it output _nothing_.  But I'm curious if there were any errors.

**Comment by chdiza** [comment]
The output is:
```
jq: error (at <unknown>): invalid gmtime representation
```

**Comment by yoichi** [comment]
c538237 breaks 1st test of optional.test
```
$ echo '"2015-03-05T23:51:47Z"' | jq 'strptime("%Y-%m-%dT%H:%M:%SZ")|strftime("%A, %B %e, %Y")'
"Wednesday, March  5, 2015"
```
It's Thursday, correctly.
