### ISSUE TITLE
Linking order confusion for libraries

### ISSUE THREAD

**Issue by muhmuhten** [stedolan/jq#1828]
`block_bind_library` (and `block_bind_each`, `block_bind_referenced`, and maybe others) traverse the binder block from first by next, so the first function declared with a given name gets used, even if the library contains another function of the same name declared later.

The parser, on the other hand, binds backwards, and later definitions "override" (really, get locked in before) those earlier in the file. This leads to an inconsistency:

```
% jq -n 'def a: 1; def a: 2; a'
2
% echo 'def a: 1; def a: 2;' > a.jq
% jq -n 'include "a"; a'
1
```

This is a pretty trifling point, but I'm leaving it here for consideration because from cursory examination, the change I suggested in https://github.com/stedolan/jq/issues/1826#issuecomment-464597334 would require doing `bind_block_referenced`s _backward_ in order to get the linkage within builtin.jq right, which seems like a good opportunity to do the same thing when linking libraries, which would (from my perspective) fix this inconsistency.

There's a bit of trickiness when a single file includes multiple libraries; the libraries need to be bound in backwards, too, I believe.

Thoughts?

**Comment by nicowilliams** [comment]
Oof.  This would be a breaking change, but we must make it.

**Comment by nicowilliams** [comment]
Fixed by @muhmuhten in #1834.

**Comment by muhmuhten** [comment]
Not fixed yet.

Another wrinkle: when we include multiple libraries, e.g.

```
# e.jq
def e: 1;
def e: 2;
```
```
# f.jq
def e: 3;
```
```
# main program
include "e";
include "f";
e
```

We probably want 3, but we actually get 1 (2 after above patch)

**Comment by muhmuhten** [comment]
The quick way to fix this is flipping the imports in the parser but that's a wtf.

We could do it in block_take_imports, but that actually does extra work...

**Comment by muhmuhten** [comment]
Actually, this behaviour is already tested since c4cc62a053f632f5daf6c40837f5dcfa01ddf590, so I guess the other way around is intentional?
