### ISSUE TITLE
scan/2 does not appear to be defined in jq 1.6 and no sample is documented

### ISSUE THREAD

**Issue by brokenregime** [stedolan/jq#2207]
scan(regex) works
scan(regex; flags) doesn't

Running under debian 8 (jessie) and Ubuntu focal (20.04.1) with jq-linux64 1.6:

$ echo '"#big #Big #bIg #bigs #biG"' | jq '.|scan("#big\\S*")'
"#big"
"#bigs"

$ echo '"#big #Big #bIg #bigs #biG"' | jq '.|scan("#big\\S*";"i")'
jq: error: scan/2 is not defined at <top-level>, line 1:
.|scan("#big\\S*";"i")  
jq: 1 compile error

Also, the online documentation for jq 1.6 shows example only for scan(regex).

Expected to get same positive results I get from test(regex; flags).

Running jq -n 'builtins' reveals the only incidence of "scan" is "scan/1".

Thanks!  Otherwise, I absolutely adore this wonderful program!

-Mike B

[edits: clarifying version of jq I'm running and added reference to 'builtins' lacking scan/2]

**Comment by itchyny** [comment]
This is resolved by #1961.

**Comment by brokenregime** [comment]
All well and good, but commit b41acdd3fddc25d6b37ccc1961fdb045b6ae6fd3 to #1961 says:

    This commit does not belong to any branch on this repository.

and scan/2 is still not implemented in jq-1.6-137-gd18b2d0-dirty, pulled and built today, 1.5 years after it was supposedly resolved, the basis for closing my report #2207.

Thanks,
-Mike
