### ISSUE TITLE
jq accepts and ignores some invalid JSON input 

### ISSUE THREAD

**Issue by radiospiel** [stedolan/jq#769]
I use `jq . path/to/file > /dev/null` in a make-based environment to validate some JSON files. This works nice, in general, but I stumbled across this one:

```
> cat test.json 
{
    "foo": "bar'
}
> jq . test.json 
> 
```  

I would expect jq to raise an error, since the input file is not valid json.

**Comment by slapresta** [comment]
Simpler reproducible case: 
```
> cat test.json
"
```

It seems to be about a string literal not being closed.

**Comment by nicowilliams** [comment]
Fixed in master.

**Comment by lukeplausin** [comment]
This issue still appears to be present in JQ 1.5 on macOS.
If I run `jq '.'` on this file I get no output and a zero exit code
```
{
  "key1": {
    "unclosedSubkey1":{
      "type":"string"
  }
}
```
